### ISSUE TITLE
csh missing in the c7 image

### ISSUE THREAD

**Issue by jopekelly** [stfc/grid-workernode#2]
Argo tests are failing regularly on arc-ce01 and arc-ce02 (both machines have the c7 image deployed). The error message is : Script exited with code 126. Could not find $PATH in the csh environment 

Investigation:
I found a worker node with both c6 and c7 containers running.  If I try:

[root@lcg2093 ~]# docker exec -it HTCJob23937452_0_slot1_9_PID16251 csh
oci runtime error: exec failed: container_linux.go:265: starting container process caused "exec: \"csh\": executable file not found in $PATH"

It fails. The same command works on a c6 container. 
I note that /usr/bin/csh is a sim-link to /usr/bin/tcsh and csh is provided by the tcsh package. 

It looks like we need to add tcsh to the c7 container.

**Comment by CatalinCondurache** [comment]
It is going to be fixed with latest stfc/grid-workernode-c7:2018-02-12.3 image (when deployed via arc-ce01 and arc-ce02)

**Comment by jrha** [comment]
Fixed in f5e94723038bb3482a7c0b12699dcc18ef563a71.
